focusbackup/app/machine/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('focusbackup.app.machine.views',
                       url(r'^$', 'overview', name="machine_overview"),
                       url(r'^logs/$', 'list_logs_all_machines', name="machine_list_all_logs"),
                       url(r'^new/$', 'new', name="machines.new"),
                       url(r'^install-instructions/$', 'install_instructions',
                           name="machines.install_instructions"),
                       url(r'^install-instructions-linux/$', 'install_instructions_linux',
                           name="machines.install_instructions_linux"),
                       url(r'^(?P<id>\w+)/view/$', 'view', name="machines.view"),
                       url(r'^(?P<id>\w+)/view/log/$', 'view_log', name="machines.view_log"),
                       url(r'^(?P<id>\w+)/view/schedules/$', 'view_schedules',
                           name="machines.view_schedules"),
                       url(r'^(?P<id>\w+)/view/backups/$', 'view_backups',
                           name="machines.view_backups"),
                       url(r'^(?P<id>\w+)/view/all_backups/schedule/(?P<schedule_id>\d+)$',
                           'all_recoverable_backups_schedule',
                           name="machines.all_recoverable_backups_schedule"),
                       url(r'^(?P<id>\w+)/edit/$', 'edit'),
                       url(r'^(?P<id>\w+)/settings/$', 'settings'),
                       url(r'^(?P<id>\w+)/toggle_busy/$', 'toggle_busy',
                           name="machines.toggle_busy"),
                       url(r'^(?P<id>\w+)/stop_schedule/(?P<schedule_id>\w+)/$', 'stop_schedule',
                           name="machines.stop_schedule"),
                       url(r'^(?P<id>\w+)/toggle_run_schedule_now/(?P<schedule_id>\w+)/$',
                           'toggle_run_schedule_now', name="machines.toggle_run_schedule_now"),
                       url(r'^(?P<id>\w+)/toggle_active/$', 'toggle_active',
                           name="machines.toggle_active"),
                       url(r'^(?P<id>\w+)/delete/$', 'delete'),
                       url(r'^(?P<id>\w+)/replace-schedules/(?P<template_id>\w+)/$',
                           'replace_schedules_with_template'),

                       url(r'^templates/$', 'templates', name="templates.overview"),
                       url(r'^(?P<id>\w+)/template/view/$', 'view_template', name="templates.view"),
                       url(r'^(?P<id>\w+)/template/view/schedules/$', 'view_template_schedules',
                           name="templates.view_schedules"),
)

focusbackup/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'focusbackup.app.machine.views.overview'),
    url(r'^machines/', include('focusbackup.app.machine.urls')),
    url(r'^backups/', include('focusbackup.app.backup.urls')),
    url(r'^storages/', include('focusbackup.app.storage.urls')),
    url(r'^customers/', include('focusbackup.app.customer.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('focusbackup.api.urls')),

    url(r'^download_current_agent/', 'focusbackup.core.views.download_current_agent'),
    url(r'^download_current_updater/', 'focusbackup.core.views.download_current_updater'),
    url(r'^download_current_installer/', 'focusbackup.core.views.download_current_installer'),
)

if 'nopassword' in settings.INSTALLED_APPS:
    urlpatterns += patterns('', url(r'^accounts/', include('nopassword.urls')))
else:
    urlpatterns += patterns('', url(r'^accounts/', include('focusbackup.app.accounts.urls')))

urlpatterns += staticfiles_urlpatterns()

focusbackup/app/machine/models.py
# -*- coding: utf-8 -*-
from copy import deepcopy
import datetime

from django.db import models, transaction, IntegrityError

from focusbackup.app.client.models import ClientVersion
from focusbackup.app.customer.models import Customer


class Machine(models.Model):
    name = models.CharField(max_length=150)
    customer = models.ForeignKey(Customer, related_name="machines")
    run_install = models.BooleanField(default=True)

    active = models.BooleanField(default=True)
    template = models.BooleanField(default=False)

    # Info from the client
    # last_connection_to_client = models.DateTimeField(blank=True, null=True,
    #                                                 default=datetime.datetime.now())

    external_ip = models.IPAddressField(default="")

    # For generating settings-file
    local_temp_folder = models.CharField(max_length=255, default="C:\\focus24\\temp\\")
    agent_folder = models.CharField(max_length=255, default="C:\\focus24\\")
    mysql_dump = models.CharField(max_length=255, default="mysqldump")

    auto_version = models.BooleanField(default=True)

    lock = models.DateTimeField(default=None, null=True, blank=True)
    lock_session = models.CharField(max_length=255, null=True, default=None)

    # Current version running on client
    current_agent_version = models.ForeignKey(ClientVersion, related_name="agent_versions",
                                              null=True)
    current_updater_version = models.ForeignKey(ClientVersion, related_name="updater_versions",
                                                null=True)

    # If not auto_version
    selected_agent_version = models.ForeignKey(ClientVersion, related_name="agent_selected",
                                               null=True, blank=True)
    selected_updater_version = models.ForeignKey(ClientVersion, related_name="updater_selected",
                                                 null=True, blank=True)

    class Meta:
        ordering = ["-active", "name", "id"]

    @property
    def last_connection_to_client(self):
        try:
            return self.logs.all()[0].datetime
        except IndexError:
            return None

    def __unicode__(self):
        return "Machine: %s, id: %s" % (self.name, self.id)

    def set_active(self, active):
        self.active = active
        self.save(update_fields=["active"])

    def set_lock(self, session=None):
        try:
            with transaction.atomic():
                self.lock = datetime.datetime.now()
                self.lock_session = session
                self.save(update_fields=["lock", "lock_session"])
                self.log("info", "lock set by %s" % session)
        except IntegrityError:
            self.log("error", "error locking..")

    def release_lock(self, session=None):
        try:
            with transaction.atomic():
                last_locked_date = self.lock
                self.lock = None
                self.lock_session = None
                self.save(update_fields=["lock", "lock_session"])
                self.log("info", "lock (from %s) released by %s" % (last_locked_date, session))
        except IntegrityError:
            self.log("error", "error unlocking..")

    def clone(self):
        copy = deepcopy(self)
        copy.pk = None
        copy.template = False
        copy.save()

        for schedule in self.schedules.all():
            schedule_copy = deepcopy(schedule)
            schedule_copy.pk = None
            schedule_copy.machine = copy
            schedule_copy.save()

            for folder in schedule.folders.all():
                folder_copy = deepcopy(folder)
                folder_copy.pk = None
                folder_copy.schedule = schedule_copy
                folder_copy.save()

            for sql in schedule.sql_backups.all():
                sql_copy = deepcopy(sql)
                sql_copy.pk = None
                sql_copy.schedule = schedule_copy
                sql_copy.save()

        return copy

    def is_up_to_date(self):
        return self.current_agent_version.current_agent \
            and self.current_updater_version.current_updater

    def lost_connection_to_client(self):
        return datetime.datetime.now() - self.last_connection_to_client > datetime.timedelta(
            minutes=20)

    def get_selected_agent_version(self):
        if self.auto_version:
            return ClientVersion.objects.get(current_agent=True)
        else:
            return self.selected_agent_version

    def get_selected_updater_version(self):
        if self.auto_version:
            return ClientVersion.objects.get(current_updater=True)
        else:
            return self.selected_updater_version

    def get_latest_stats(self):
        return self.stats.all()[0:20].reverse()

    def get_latest_logs(self):
        return self.logs.all().order_by("-id")[0:8]

    def log(self, log_type, text):
        machine_log = MachineLog(machine=self,
                                 datetime=datetime.datetime.now(),
                                 type=log_type,
                                 text=text)

        machine_log.save()

        if not self.active:
            self.set_active(True)

        return machine_log

    def delayed_schedules(self):
        schedules = []

        for schedule in self.schedules.all():
            if schedule.is_delayed():
                schedules.append(schedule.id)

        return self.schedules.filter(id__in=schedules)

    def get_latest_backups(self):
        return self.backups.select_related("schedule") \
                   .prefetch_related("schedule__folders", "schedule__sql_backups") \
                   .order_by("-id")[0:8]

    def running_backup(self):
        for schedule in self.schedules.all():
            if schedule.running_backup:
                return True
        return False

    def running_restore(self):
        for schedule in self.schedules.all():
            if schedule.running_restore:
                return True
        return False

    def is_busy(self):
        return self.running_restore() or self.running_backup() or self.lock is not None

    def get_last_backup_time(self):
        next_backup_time = None
        for schedule in self.schedules.all():
            if not next_backup_time:
                next_backup_time = schedule.get_last_backup_time()
            elif schedule.get_next_run_time() > next_backup_time:
                next_backup_time = schedule.get_last_backup_time()

        return next_backup_time

    def get_next_backup_time(self):
        next_backup_time = None
        for schedule in self.schedules.all():
            if not next_backup_time:
                next_backup_time = schedule.get_next_backup_time()
            elif schedule.get_next_backup_time() < next_backup_time:
                next_backup_time = schedule.get_next_backup_time()

        return next_backup_time


class MachineStats(models.Model):
    datetime = models.DateTimeField(default=datetime.datetime.now())
    machine = models.ForeignKey(Machine, related_name="stats")

    load_average = models.DecimalField(decimal_places=3, max_digits=50)

    cpu_system = models.DecimalField(decimal_places=3, max_digits=50)
    cpu_user = models.DecimalField(decimal_places=3, max_digits=50)
    cpu_stolen = models.DecimalField(decimal_places=3, max_digits=50)

    mem_used = models.DecimalField(decimal_places=3, max_digits=50, default=0)
    mem_free = models.DecimalField(decimal_places=3, max_digits=50, default=0)

    class Meta:
        ordering = ['-id']


class MachineProcessStats(models.Model):
    datetime = models.DateTimeField(default=datetime.datetime.now())
    machine = models.ForeignKey(Machine)

    pid = models.IntegerField()
    name = models.CharField(max_length=100)
    user = models.CharField(max_length=100)

    cpu_usage = models.DecimalField(decimal_places=3, max_digits=10)
    mem_usage = models.DecimalField(decimal_places=3, max_digits=10)

    class Meta:
        ordering = ['-id']


log_types = (
    ('info', 'INFO'),
    ('error', 'ERROR'),
    ('warning', 'WARNING')
)


class MachineLog(models.Model):
    machine = models.ForeignKey(Machine, related_name="logs")
    datetime = models.DateTimeField()
    text = models.TextField()
    type = models.CharField(max_length=10, choices=log_types)

    class Meta:
        ordering = ["-id"]

    def __unicode__(self):
        return "%s %s %s" % (self.machine, self.datetime, self.text)

focusbackup/app/machine/forms.py
# -*- coding: utf-8 -*-
from focusbackup.app.backup.models import Machine
from focusbackup.core.forms import BootstrapModelForm


class MachineForm(BootstrapModelForm):
    def __init__(self, *args, **kwargs):
        user = None
        if 'user' in kwargs:
            user = kwargs['user']
            del (kwargs['user'])

        super(MachineForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['customer'].queryset = user.profile.get_customers()

    class Meta:
        model = Machine
        fields = ('id', 'name', 'customer', 'local_temp_folder', 'agent_folder', 'template')

project/templates/machines/form.html
{% extends "machines/base.html" %}
{% block main %}
    {% include "form_fields.html" %}

    <script>
        $(document).ready(function () {
            function hide_select_boxes(hide) {

                if (hide) {
                    $("#id_selected_agent_version").parent().parent().hide();
                    $("#id_selected_updater_version").parent().parent().hide();
                }

                else {
                    $("#id_selected_agent_version").parent().parent().show();
                    $("#id_selected_updater_version").parent().parent().show();
                }
            }

            if ($("#id_auto_version").attr("checked")) {
                hide_select_boxes(true);
            }

            $("#id_auto_version").click(function () {
                if (this.checked) {
                    hide_select_boxes(true);
                } else {
                    hide_select_boxes(false)
                }
            });
        });
    </script>

{% endblock %}

project/templates/machines/list.html
{% extends "machines/base.html" %}
{% load i18n %}

{% block main %}


    <section id="machines">

        <table class="table-bordered table table-striped table-condensed">
            <thead>

            <tr>
                <th style="width:10%;">ID</th>
                <td style="width:15%;">Name</td>
                <th style="width:20%;">Last connection</th>
                <th style="width:30%">Last backup time</th>
                <th style="width:30%">Updater version</th>
                <th style="width:30%">Status</th>
            </tr>

            </thead>

        </table>

        {% for customer in company.customers.all %}

            <h4>{{ customer.name }}</h4>

            <table class="table-bordered table table-striped table-condensed">

                <tbody>

                {% for machine in customer.machines.all %}

                    <tr>
                        <td style="width:10%;">{{ machine.machine_id }}</td>
                        <td style="width:15%;"><a href="{% url view_machine machine.id  %}">{{ machine.name }}</a>
                        </td>
                        <td style="width:20%;">{{ machine.last_connection_to_client }}</td>
                        <td>{{ machine.get_last_backup_time }}</td>
                        <td>{{ machine.current_updater_version }}</td>
                        <td>

                            {% if machine.running_backup %}

                                <span class="label label-info">{% trans "running backup" %}</span>

                            {% else %} {% if machine.running_restore %}
                                <span class="label label-info">{% trans "running restore" %}</span>


                            {% else %}

                                <span class="label label-success">{% trans "OK" %}</span>

                            {% endif %}
                            {% endif %}

                        </td>
                    </tr>

                {% endfor %}

                </tbody>

            </table>

        {% endfor %}

    </section>

    <hr>

    <footer>
        <p></p>
    </footer>

{% endblock %}

project/templates/machines/view.htm.html
viser {{ machine }}

project/templates/machines/view.html
{% extends "machines/base.html" %}
{% load i18n %}

{% block main %}

    <section id="responsive">


        <div class="page-header">
            <h3>{{ machine.name }}</h3>
        </div>


        <div class="row">

            <div class="span6">
                <table class="table table-bordered table-striped">

                    <tbody>

                    <tr>
                        <td>{% trans "Machine ID" %}</td>
                        <td>{{ machine.machine_id }}</td>
                    </tr>

                    <tr>
                        <td>Name</td>
                        <td>{{ machine.name }}</td>
                    </tr>

                    <tr>
                        <td>Customer</td>
                        <td>{{ machine.customer.name }}</td>
                    </tr>

                    <tr>
                        <td>Last connection to client</td>
                        <td>{{ machine.last_connection_to_client }}</td>
                    </tr>

                    <tr>
                        <td>Auto version</td>
                        <td>{{ machine.auto_version }}</td>
                    </tr>
                    <tr>
                        <td>Current agent version</td>
                        <td>{{ machine.current_agent_version }}</td>
                    </tr>
                    <tr>
                        <td>Auto updater version</td>
                        <td>{{ machine.current_updater_version }}</td>
                    </tr>

                    </tbody>
                </table>

            </div>

            <div class="span6">

                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Date start" %}</th>
                        <th>{% trans "Date stop" %}</th>
                        <th>{% trans "Schedule" %}</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for schedule in machine.schedules.all %}

                        <tr>
                            <td>{{ backup.time_started|date:"d.m.Y H:i" }}</td>
                            <td>{{ backup.time_ended|date:"d.m.Y H:i" }}</td>
                            <td>{{ backup.schedule.name }}</td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>




        </div>

        <div class="row">
            <div class="span6">

                <h2>{% trans "Backups" %}</h2>

                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Date start" %}</th>
                        <th>{% trans "Date stop" %}</th>
                        <th>{% trans "Schedule" %}</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for backup in machine.get_latest_backups %}

                        <tr>
                            <td>{{ backup.time_started|date:"d.m.Y H:i" }}</td>
                            <td>{{ backup.time_ended|date:"d.m.Y H:i" }}</td>
                            <td>{{ backup.schedule.name }}</td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="span6">
                <h2>{% trans "Log" %}</h2>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>{% trans "Date" %}</th>
                        <th>{% trans "Description" %}</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for log in machine.get_latest_logs %}

                        <tr>
                            <td>{{ log.datetime|date:"d.m.Y H:i" }}</td>
                            <td>{{ log.text }}</td>
                        </tr>

                    {% endfor %}


                    </tbody>
                </table>


            </div>
        </div>


    </section>

{% endblock %}